# Generated by Django 4.2.2 on 2023-07-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('price', models.CharField(max_length=100, verbose_name='price')),
                ('image', models.ImageField(upload_to='ad_covers/', verbose_name='image')),
                ('status_product', models.CharField(choices=[('0', 'Need repair'), ('1', 'Worked'), ('2', 'Like new'), ('3', 'New')], max_length=10, verbose_name='status product')),
                ('location', models.TextField(verbose_name='location')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='phone')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('confirmation', models.BooleanField(default=False, verbose_name='confirmation')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ManyToManyField(blank=True, default=None, related_name='categories', to='ads.category', verbose_name='category')),
                ('sign', models.ManyToManyField(blank=True, default=None, related_name='signs', to=settings.AUTH_USER_MODEL, verbose_name='sign')),
            ],
        ),
    ]
