# Generated by Django 4.2.2 on 2023-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='confirmation',
            field=models.BooleanField(default=False, help_text='this is for admin', verbose_name='confirmation'),
        ),
    ]
