# Generated by Django 4.2.2 on 2023-07-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status_product',
            field=models.CharField(choices=[('need repair', 'Need repair'), ('worked', 'Worked'), ('like new', 'Like new'), ('new', 'New')], max_length=30, verbose_name='status product'),
        ),
    ]
