# Generated by Django 4.2.2 on 2023-07-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_status_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime deleted'),
        ),
        migrations.AddField(
            model_name='ad',
            name='delete_with',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('staff', 'Staff'), ('expired', 'Expired'), ('other', 'Other')], max_length=15, null=True, verbose_name='delete with'),
        ),
        migrations.AddField(
            model_name='ad',
            name='expiration_date',
            field=models.DateTimeField(null=True, verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='is delete'),
        ),
    ]
