# Generated by Django 4.2.2 on 2023-07-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverify',
            name='count_otp',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='count otp'),
        ),
        migrations.AddField(
            model_name='codeverify',
            name='limit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='limit time'),
        ),
    ]
